Repository CamelliaCommunity/Wiki, pull requests merged in 2024-01, with the labels that each got.

#90 Create Blog Post “2024-01-01-gib-campaign-dlc-343”
  postsBlog/_posts/2024-01-01-gib-campaign-dlc-343.md
Labels: decap-cms/pending_publish

#95 Create Included Post “2024-01-04-test”
  postsInclude/_posts/2024-01-04-test.md
Labels: decap-cms/pending_publish

#96 Create Page “test/index”
  content/test/index.md
Labels: decap-cms/pending_publish

#97 Create Page “test/{{year}}-{{month}}-{{day}}-{{slug}}”
  content/test/{{year}}-{{month}}-{{day}}-{{slug}}.md
Labels: decap-cms/pending_publish

#98 Create Included Post “makeone/index”
  postsInclude/_posts/uploads/makeone/index.md
Labels: decap-cms/pending_publish

#99 Create Included Post “fishtaco/makeanother/index”
  postsInclude/_posts/uploads/fishtaco/makeanother/index.md
Labels: decap-cms/pending_publish

#100 Create Included Post “camelliaserver/index”
  postsInclude/_posts/uploads/camelliaserver/index.md
Labels: decap-cms/pending_publish

#101 Update Included Post “camelliaserver/index”
  postsInclude/_posts/uploads/camelliaserver/meetings/index.md
Labels: decap-cms/pending_publish

#102 Create Included Post “camelliaserver/camelliamonthly/index”
  postsInclude/_posts/uploads/camelliaserver/camelliamonthly/index.md
Labels: decap-cms/pending_publish

#108 Create News Post “2024-01-06-announcing-domain-change”
  postsNews/_posts/2024-01-06-announcing-domain-change.md
Labels: decap-cms/pending_publish

#109 Update News Post “2024-01-06-announcing-domain-change”
  postsNews/_posts/2024-01-06-announcing-domain-change.md
Labels: decap-cms/pending_publish

#110 Update News Post “2024-01-06-announcing-domain-change”
  postsNews/_posts/2024-01-06-announcing-domain-change.md
Labels: decap-cms/pending_publish

#111 Update News Post “2024-01-06-announcing-domain-change”
  postsNews/_posts/2024-01-06-announcing-domain-change.md
Labels: decap-cms/pending_publish

#117 Make the CMS preview mimic the actual page design
  admin/index.html
  admin/mixin.js
  admin/style/decap-preview.css
  admin/style/decap-preview.css.map
  admin/style/scss/decap-preview.scss
Labels: enhancement

#116 Update Included Post “camelliaServer/2023-11-26-meetings”
  postsInclude/_posts/camelliaServer/2023-11-26-meetings.md
Labels: decap-cms/pending_publish

#122 Update Legacy Files “about”
  about.md
Labels: decap-cms/pending_publish

#124 Create Blog Post “2024-01-12-adobe-escape”
  postsBlog/_posts/2024-01-12-adobe-escape.md
Labels: decap-cms/pending_publish

#125 Update Blog Post “2024-01-12-adobe-escape”
  postsBlog/_posts/2024-01-12-adobe-escape.md
Labels: decap-cms/draft

#126 Update Blog Post “2023-12-18-figma-didnt-merge-with-adobe-and-im-happy”
  postsBlog/_posts/2023-12-18-figma-didnt-merge-with-adobe-and-im-happy.md
Labels: decap-cms/pending_publish

#132 Create Blog Post “2024-01-17-full-flavor”
  postsBlog/_posts/2024-01-17-full-flavor.md
Labels: decap-cms/pending_publish

#142 Update Included Post “2024-01-19-incomplete-pages”
  postsInclude/_posts/2024-01-19-incomplete-pages.md
Labels: decap-cms/pending_publish

#144 Update Wiki Post “2023-12-11-camellia-server”
  postsWiki/_posts/2023-12-11-camellia-server.md
Labels: decap-cms/pending_publish

#148 Update Wiki Post “2023-12-11-contributing”
  postsWiki/_posts/2023-12-11-contributing.md
Labels: decap-cms/pending_publish

#159 Update Included Post “camellia/2023-11-16-discography”
  postsInclude/_posts/camellia/2023-11-16-discography.md
Labels: decap-cms/pending_publish

#165 Update Included Post “camellia/albums/2024-01-22-snacko-original-game-soundtrack”
  postsInclude/_posts/camellia/albums/2024-01-22-snacko-original-game-soundtrack.md
Labels: decap-cms/pending_publish

#167 Update Included Post “camellia/albums/2024-01-23-infiniti-mofulity”
  postsInclude/_posts/camellia/albums/2024-01-23-infiniti-mofulity.md
Labels: decap-cms/pending_publish

#173 Update Included Post “camellia/albums/2023-11-16-discography”
  postsInclude/_posts/camellia/albums/2023-11-16-discography.md
Labels: decap-cms/pending_publish

#174 Create Legal Documents
  _includes/footer.html
  assets/_scss/styles.scss
  assets/css/styles.css
  assets/css/styles.css.map
  postsWiki/_posts/2024-01-27-privacy-policy.md
  postsWiki/_posts/2024-01-27-terms-of-service.md
Labels: decap-cms/draft

#175 Update Wiki Post “2024-01-27-privacy-policy”
  postsWiki/_posts/2024-01-27-privacy-policy.md
Labels: decap-cms/pending_publish

#176 Update Wiki Post “2024-01-27-privacy-policy”
  postsWiki/_posts/2024-01-27-privacy-policy.md
Labels: decap-cms/pending_publish

#177 Update Included Post “camellia/albums/2023-11-16-discography”
  postsInclude/_posts/camellia/albums/2023-11-16-discography.md
Labels: decap-cms/pending_publish

#181 Update Wiki Post “2024-01-27-privacy-policy”
  postsWiki/_posts/2024-01-27-privacy-policy.md
Labels: decap-cms/pending_publish
